### ISSUE TITLE
ClassNotFoundException: org.jooq.codegen.KotlinGenerator

### ISSUE THREAD

**Issue by patryk-marcin-zielinski** [revolut-engineering/jooq-plugin#16]
Hello,

Probably it is problem of my configuration, but I can't change generator to Kotlin.

```
Caused by: java.lang.ClassNotFoundException: org.jooq.codegen.KotlinGenerator
        at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:926)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:377)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at com.revolut.jooq.GenerateJooqClassesTask.generateJooqClasses(GenerateJooqClassesTask.kt:186)
```

Gradle configuration
```
tasks {
    generateJooqClasses {
        basePackageName = "com.test.infrastructure.database.jooq"
        inputDirectory.setFrom(project.files("src/main/resources/db/migration"))
        outputDirectory.set(project.layout.buildDirectory.dir("generated-jooq"))
        excludeFlywayTable = true
        customizeGenerator {
            name = "org.jooq.codegen.KotlinGenerator"
        }
    }
}
```

Any idea what could be the problem?

Regards
Patryk

**Comment by patryk-marcin-zielinski** [comment]
Ok I found problem, it seems like 0.3.5 version doesn't contains "org.jooq.codegen.KotlinGenerator". Can you guys release latest version?
